import Header from '@/components/Header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/globals.css';
import '../styles/reset.css';
import 'react-toastify/ReactToastify.css';
import AuthSession from './_components/AuthSession';
import Provider from './_components/CampProvider';
import RealHeader from './_components/RealHeader';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '캠퍼스팟 (Camperspot)',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={inter.className}>
        <AuthSession>
          <Provider>
            <div id='modal'></div>
            <Header />
            <RealHeader />
            {children}
          </Provider>
          <ToastContainer />
        </AuthSession>
      </body>
    </html>
  );
}
